version: '3.5'

services:
  db:
    image: postgres:14.1-alpine

    # For debugging statements
    command: ['postgres', '-c', 'log_statement=all']

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playground

    # Use RAM to increased performance
    tmpfs: /var/lib/postgresql/data

    ports:
      - '54320:5432'
